### ISSUE TITLE
Buttons does not inherit body element css color

### ISSUE THREAD

**Issue by rodrigosuelli** [rodrigosuelli/portfolio-web#2]
To fix, in the global css file add the property color: inherit to the button element selector.

E.g.

```css
button {
  color: inherit;
}
```
